"""empty base

Revision ID: 96a0d652f220
Revises:
Create Date: 2026-08-29 15:53:48.950323

"""

# revision identifiers, used by Alembic.
revision: str = "96a0d652f220"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
